checks:
  go: true
build:
  nodes:
    analysis:
      environment:
        go:
          version: go1.14.7
      tests:
        override:
          - go-scrutinizer-run
          - golint-run
          - govet-run
filter:
  excluded_paths:
    - "*_test.go"
  dependency_paths:
    - "vendor/"
