checks:
  go: true
build:
  nodes:
    analysis:
      environment:
        go:
          version: go1.15
      tests:
        override:
          - go-scrutinizer-run
          - golint-run
          - govet-run
    tests:
      dependencies:
        befor:
          - rm -r ./vendor
      environment:
        go:
          version: go1.15
      tests:
        override:
          - command: go test ./... -coverprofile=c.out
            coverage:
              file: c.out
              format: go-cc
filter:
  excluded_paths:
    - "*_test.go"
  dependency_paths:
    - "vendor/"
